{
 "title": "WordPress dashboard",
 "description": "A dashboard displaying WordPress site metrics. Used with wordpress-exporter https://github.com/aorfanos/wordpress-exporter",
 "tags": [
  "wordpress",
  "web"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Website",
    "query": {
     "query": "label_values(exported_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://pngimg.com/uploads/wordpress/wordpress_PNG6.png\" alt=\"WordPress logo png\">"
   }
  },
  {
   "title": "Plugins",
   "type": "stat",
   "description": "WordPress plugin count",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wordpress_plugin_count{exported_instance=~\"$Website\"}",
     "legendFormat": "{{ exported_instance }}"
    }
   ]
  },
  {
   "title": "Themes",
   "type": "stat",
   "description": "WordPress theme count",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wordpress_theme_count{exported_instance=~\"$Website\"}",
     "legendFormat": "{{ exported_instance }}"
    }
   ]
  },
  {
   "title": "Comments",
   "type": "stat",
   "description": "WordPress comment count",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wordpress_comment_count{exported_instance=~\"$Website\"}",
     "legendFormat": "{{ exported_instance }}"
    }
   ]
  },
  {
   "title": "Categories",
   "type": "stat",
   "description": "WordPress category count",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wordpress_category_count{exported_instance=~\"$Website\"}",
     "legendFormat": "{{ exported_instance }}"
    }
   ]
  },
  {
   "title": "Pages",
   "type": "stat",
   "description": "WordPress page count",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wordpress_page_count{exported_instance=~\"$Website\"}",
     "legendFormat": "{{ exported_instance }}"
    }
   ]
  },
  {
   "title": "Media",
   "type": "stat",
   "description": "WordPress media count",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wordpress_media_count{exported_instance=~\"$Website\"}",
     "legendFormat": "{{ exported_instance }}"
    }
   ]
  },
  {
   "title": "Users",
   "type": "stat",
   "description": "WordPress user count",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wordpress_user_count{exported_instance=~\"$Website\"}",
     "legendFormat": "{{ exported_instance }}"
    }
   ]
  },
  {
   "title": "Tags",
   "type": "stat",
   "description": "WordPress tag count",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wordpress_tag_count{exported_instance=~\"$Website\"}",
     "legendFormat": "{{ exported_instance }}"
    }
   ]
  }
 ]
}